//! Device linking screen — two modes:
//!
//! **SCAN** tab (default): enter a link token from another device.
//!   Flow: other device → Settings → Add Replica → generates token
//!         user types/pastes it here → Enter → ConfirmDeviceLink RPC
//!
//! **SHOW** tab: this device generated a link token; display it as a QR code
//!   for the new device to scan with the mobile app or another TUI instance.

use ratatui::{
    buffer::Buffer,
    layout::Rect,
    style::{Color, Modifier, Style},
    text::{Line, Span},
    widgets::{Block, Borders, Paragraph, Widget},
};

use super::qr_widget::QrWidget;

#[derive(Debug, Clone, PartialEq)]
pub enum DeviceLinkTab {
    /// Enter a token generated by another device.
    Scan,
    /// Show a QR / token for this device so another device can scan it.
    Show,
}

pub struct DeviceLinkScreen {
    pub tab: DeviceLinkTab,
    /// Token typed by the user (SCAN tab).
    pub token: String,
    /// Token generated by this device to display (SHOW tab). Set by the app
    /// after calling the GenerateDeviceLink RPC.
    pub own_token: Option<String>,
    pub status: Option<String>,
    pub is_error: bool,
}

impl DeviceLinkScreen {
    pub fn new() -> Self {
        Self {
            tab: DeviceLinkTab::Scan,
            token: String::new(),
            own_token: None,
            status: Some("Paste or type the link token shown on your other device".into()),
            is_error: false,
        }
    }

    pub fn push_char(&mut self, c: char) {
        if self.tab == DeviceLinkTab::Scan && self.token.len() < 64 {
            self.token.push(c);
        }
    }

    pub fn pop_char(&mut self) {
        if self.tab == DeviceLinkTab::Scan {
            self.token.pop();
        }
    }

    /// Switch between SCAN and SHOW tabs (called on Tab key).
    pub fn toggle_tab(&mut self) {
        self.tab = match self.tab {
            DeviceLinkTab::Scan => DeviceLinkTab::Show,
            DeviceLinkTab::Show => DeviceLinkTab::Scan,
        };
    }

    pub fn set_status(&mut self, msg: impl Into<String>, error: bool) {
        self.status = Some(msg.into());
        self.is_error = error;
    }

    pub fn clear_status(&mut self) {
        self.status = None;
        self.is_error = false;
    }
}

impl Widget for &DeviceLinkScreen {
    fn render(self, area: Rect, buf: &mut Buffer) {
        // ── Tab bar ───────────────────────────────────────────────────────────
        let tab_scan = if self.tab == DeviceLinkTab::Scan {
            Span::styled(
                " [SCAN] ",
                Style::default().fg(Color::Black).bg(Color::Cyan),
            )
        } else {
            Span::styled(" [SCAN] ", Style::default().fg(Color::DarkGray))
        };
        let tab_show = if self.tab == DeviceLinkTab::Show {
            Span::styled(
                " [SHOW QR] ",
                Style::default().fg(Color::Black).bg(Color::Cyan),
            )
        } else {
            Span::styled(" [SHOW QR] ", Style::default().fg(Color::DarkGray))
        };
        let tab_hint = Span::styled("  Tab=switch tab", Style::default().fg(Color::DarkGray));

        let tab_line = Line::from(vec![tab_scan, tab_show, tab_hint]);
        let tab_w = area.width;
        Paragraph::new(tab_line).render(
            Rect {
                x: area.x,
                y: area.y,
                width: tab_w,
                height: 1,
            },
            buf,
        );

        let content_area = Rect {
            x: area.x,
            y: area.y + 2,
            width: area.width,
            height: area.height.saturating_sub(2),
        };

        match self.tab {
            DeviceLinkTab::Scan => self.render_scan(content_area, buf),
            DeviceLinkTab::Show => self.render_show(content_area, buf),
        }
    }
}

impl DeviceLinkScreen {
    fn render_scan(&self, area: Rect, buf: &mut Buffer) {
        const TITLE: &str = " Link existing account — enter token ";
        const HINT: &str = "Enter=confirm   Esc=back   q=quit";

        let total_h = 1u16 + 2 + 3 + 1 + 1 + 1 + 1;
        let v_offset = area.height.saturating_sub(total_h) / 2;
        let mut y = area.y + v_offset;

        let tw = TITLE.len() as u16;
        let tx = area.x + area.width.saturating_sub(tw) / 2;
        Paragraph::new(TITLE)
            .style(
                Style::default()
                    .fg(Color::Cyan)
                    .add_modifier(Modifier::BOLD),
            )
            .render(
                Rect {
                    x: tx,
                    y,
                    width: tw.min(area.width),
                    height: 1,
                },
                buf,
            );
        y += 2;

        let field_w = 50u16.min(area.width.saturating_sub(4));
        let field_x = area.x + area.width.saturating_sub(field_w) / 2;
        Paragraph::new(format!("{}_", self.token))
            .block(
                Block::default()
                    .title(" Link Token ")
                    .borders(Borders::ALL)
                    .border_style(Style::default().fg(Color::Cyan)),
            )
            .style(Style::default().fg(Color::White))
            .render(
                Rect {
                    x: field_x,
                    y,
                    width: field_w,
                    height: 3,
                },
                buf,
            );
        y += 4;

        if let Some(ref msg) = self.status {
            let color = if self.is_error {
                Color::Red
            } else {
                Color::DarkGray
            };
            let sx = area.x + area.width.saturating_sub(msg.len() as u16) / 2;
            Paragraph::new(msg.as_str())
                .style(Style::default().fg(color))
                .render(
                    Rect {
                        x: sx,
                        y,
                        width: (msg.len() as u16).min(area.width),
                        height: 1,
                    },
                    buf,
                );
            y += 2;
        }

        let hx = area.x + area.width.saturating_sub(HINT.len() as u16) / 2;
        Paragraph::new(HINT)
            .style(Style::default().fg(Color::DarkGray))
            .render(
                Rect {
                    x: hx,
                    y,
                    width: (HINT.len() as u16).min(area.width),
                    height: 1,
                },
                buf,
            );
    }

    fn render_show(&self, area: Rect, buf: &mut Buffer) {
        match &self.own_token {
            None => {
                // Token not yet generated — show loading hint
                let msg = "Generating link token…";
                let x = area.x + area.width.saturating_sub(msg.len() as u16) / 2;
                let y = area.y + area.height / 2;
                Paragraph::new(msg)
                    .style(Style::default().fg(Color::DarkGray))
                    .render(
                        Rect {
                            x,
                            y,
                            width: msg.len() as u16,
                            height: 1,
                        },
                        buf,
                    );
            }
            Some(token) => {
                // Show QR code centred in the available area
                let caption = "Scan with Construct iOS app or another device";
                QrWidget::new(token).caption(caption).render(area, buf);

                // Token text below (for manual entry fallback)
                let token_display = format!("Token: {}", token);
                let td_w = token_display.len() as u16;
                let tx = area.x + area.width.saturating_sub(td_w) / 2;
                let ty = area.y + area.height.saturating_sub(1);
                Paragraph::new(token_display.as_str())
                    .style(Style::default().fg(Color::DarkGray))
                    .render(
                        Rect {
                            x: tx,
                            y: ty,
                            width: td_w.min(area.width),
                            height: 1,
                        },
                        buf,
                    );
            }
        }
    }
}
